#! /usr/bin/env python
# encoding: utf-8
#
# PCIe Benchmark App
#

import builditems
import buildver
import software.firmware.fdt as fdt

sources = [
    'cpuuse.cpp',
    'dma.cpp',
    'dma-mem.cpp',
    'io.cpp',
    'logging.cpp',
]

includes = ['../include/']

defines = []

cflags = []

cxxflags = []


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='app_framework',
                features='cxx',
                source=sources,
                includes=builditems.get_includes(bld, includes),
                cflags=builditems.get_cflags(bld, cflags),
                cxxflags=builditems.get_cxxflags(bld, cxxflags),
                defines=builditems.get_defines(bld, defines))
