#! /usr/bin/env python
# encoding: utf-8
#
# PCIe Benchmark App
#

import builditems
import buildver
import software.firmware.fdt as fdt

sources = [
    'init.c',
    'network.cpp',
    'app-build-id.c',
    'bspinit.c',
    'pl.cpp',
    'main.cpp',
]

includes = ['../include/']

defines = []

cflags = []


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    buildver.build(bld)

    bld.objects(target='app_platform',
                features='cxx',
                source=sources,
                includes=builditems.get_includes(bld, includes),
                cflags=builditems.get_cflags(bld, cflags),
                defines=builditems.get_defines(bld, defines))
